### ISSUE TITLE
Approximate Training GPU hours

### ISSUE THREAD

**Issue by Mingyuan1997** [vinid/path_eval#10]
Thanks for your great work and your contribution in making it public.

May I ask the approximate training time of your model and your training GPU configurations? And are there any suggestions or scripts for your amazing twitter scraping contributions?

Best.

**Comment by vinid** [comment]
Hello! thanks for your interest!

We trained models on a bunch of different GPUs (e.g., A40s), usually training time is under 10 hours, but it mostly depends on the number of epochs and how many validations every epoch.

Unfortunately, Twitter has changed its API policy, you can look up the requirements here: https://developer.twitter.com/en/docs/twitter-api

If you get access to the API, tweepy works great (e.g., [see this](https://docs.tweepy.org/en/stable/api.html#tweepy.API.lookup_statuses)). for downloading tweets.
