### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jamesdolezal** [vinid/path_eval#11]
Thank you for sharing your code and pretrained weights! This looks like it will be an excellent resource for research.

I'm one of the maintainers of a deep learning pathology toolkit (https://github.com/jamesdolezal/slideflow), and I'd like to integrate your model & weights as a pretrained feature extractor. It doesn't look like you've included a license for this code repository, and without a license, others are prohibited from redistribution, modification, and use. Have you considered how you would like this code to be licensed?

Thank you again for your work and for sharing your code!

James

**Comment by vinid** [comment]
Hello! thanks so much for your interest!

Since we used twitter data collected with the academic API, we plan to release this under a non-commercial license (probably [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/)). hope this helps!

**Comment by jamesdolezal** [comment]
Excellent! Thanks for the update.
