### ISSUE TITLE
Where is the original text tag？

### ISSUE THREAD

**Issue by BlackPPP** [vinid/path_eval#12]
Where is the original text tag？

**Comment by vinid** [comment]
Hello!

Could you share some more details? tysm!

**Comment by ppanzx** [comment]
> Hello!
> 
> Could you share some more details? tysm!

Could you release the post-processed caption for each image in the dataframe_208k.csv?

**Comment by vinid** [comment]
Hi, 

No we cannot do that unfortunately. Twitter allow us only to share tweet ids (this is true for most if not all twitter datasets)
