### ISSUE TITLE
Will the processed dataset be released?

### ISSUE THREAD

**Issue by Weiqin-Zhao** [vinid/path_eval#13]
Hi, I am very interested in you excellent work. I am just curious will you released the process image-text dataset in the future?

**Comment by vinid** [comment]
Hello! Thanks so much!

Data is available here: https://drive.google.com/drive/folders/1b5UT8BzUphkHZavRG-fmiyY9JWYIWZER

**Comment by Weiqin-Zhao** [comment]
> Hello! Thanks so much!
> 
> Data is available here: https://drive.google.com/drive/folders/1b5UT8BzUphkHZavRG-fmiyY9JWYIWZER

Many thanks!
