### ISSUE TITLE
Will you make the training data public?

### ISSUE THREAD

**Issue by ekvall93** [vinid/path_eval#14]
Hello, 

Excellent code & article! I really appreciate this work. 

Will you make the training data public? 

Best regards,
Markus

**Comment by vinid** [comment]
Hello! Thanks so much!

Data is available here: https://drive.google.com/drive/folders/1b5UT8BzUphkHZavRG-fmiyY9JWYIWZER

**Comment by ekvall93** [comment]
You're the best! Thanks
