### ISSUE TITLE
How can i get text feature  of all text instand of the every word feature?

### ISSUE THREAD

**Issue by Least1924** [vinid/path_eval#15]
code liske this:

```
p_model = PLIP("./vinid/plip")

txt='asdfasdfasdfasdfasdfadfasfasfasfasfasfsfsfasdfasdfasdfasfdfasdfadfasdfasdfasdfasdfasdfasdfafaf'
txt_feature = p_model.encode_text(text=txt,batch_size=1)
print(txt_feature.shape)
            
image_feature = p_model.encode_images(images=['./1.png',batch_size=1)
print(image_feature.shape)
```
get the output is:
```
(94, 512)
(1,512)
```
how to get the txt_feature as it's shape is (1,512)?

please help!

**Comment by vinid** [comment]
Hello!!

The encode_texts methods accepts a list as input parameter.

You should pass [txt] so that it recognizes that you want to embed the entire string.

Let me know if this helps!

**Comment by Least1924** [comment]
> Hello!!
> 
> The encode_texts methods accepts a list as input parameter.
> 
> You should pass [txt] so that it recognizes that you want to embed the entire string.
> 
> Let me know if this helps!

yes,it works!  thx a lot!
