### ISSUE TITLE
HTTP Error 503 : Service Unavailable when downloading mtdp models

### ISSUE THREAD

**Issue by musk007** [vinid/path_eval#17]
Thank you for sharing your research.
I am facing the above mentioned error whenever I try to download the mtdp pretrained weights using the urls in the code.

Thank you for your time

**Comment by vinid** [comment]
Hello and thanks! :)

To which link are you referring to?

**Comment by musk007** [comment]
The following links :
"https://dox.uliege.be/index.php/s/kvABLtVuMxW8iJy/download"
"https://dox.uliege.be/index.php/s/G72InP4xmJvOrVp/download"

**Comment by vinid** [comment]
Unfortunately those are not our resources and we have thus no control over those links. You should probably reach out to the authors of that work if you need those weights.

**Comment by musk007** [comment]
Thank you for your help.
