### ISSUE TITLE
PLIP Model Weights (.pt file)

### ISSUE THREAD

**Issue by asif-hanif** [vinid/path_eval#18]
Hi @vinid 
Thanks for great work.
Could you please provide .pt file of PLIP model. I can weights on HuggingFace but they do not work with PLIP model of current repo.

**Comment by vinid** [comment]
Hello! Thanks!

Yes, you are right! Our code is based on the original CLIP. We converted the weights to the HF format after training

**Comment by asif-hanif** [comment]
Thanks for the response.
May I request to get PLIP weights based on original CLIP?

**Comment by vinid** [comment]
Not sure we still have those (having all in HF format is easier); i will check
