### ISSUE TITLE
Would you please share the code of  scraping twitter ?

### ISSUE THREAD

**Issue by AlfredQin** [vinid/path_eval#19]
Hi, thanks for your great work! I don't find the code of scraping the twitter to construct the proposed dataset. Could you please share that  so that I can reconstruct the dataset for further study ! Thank you !

**Comment by huangzhii** [comment]
There are several updates regarding Twitter API. Please refer to official Twitter (now X) API web page: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api
