### ISSUE TITLE
May I ask if it is possible to publicly disclose the original images and corresponding text of the dataset

### ISSUE THREAD

**Issue by fffsbx** [vinid/path_eval#20]
May I ask if it is possible to publicly disclose the original images and corresponding text of the dataset

**Comment by vinid** [comment]
Hello!

Thanks for your interest! Due to the fact that the images come from Twitter we cannot share them directly. We can only share the IDs.

**Comment by huangzhii** [comment]
You can check out the list of Twitter IDs of pathology images here: https://tinyurl.com/openpathdata.

We strictly adhere to the policy and privacy regulation of Twitter (now X). Please read our **Privacy statement**:

In accordance with the privacy and control policy of Twitter, we hereby declare that the data redistributed by us shall only comprise of Tweet IDs. The Tweet IDs will be employed to establish a linkage with the original Twitter post, as long as the original post is still accessible. The hyperlink will cease to function if the user deletes the original post. It is important to note that all tweets displayed on our service have already been classified as non-sensitive by Twitter. It is strictly prohibited to redistribute any content apart from the Tweet IDs. Any distribution carried out must adhere to the laws and regulations applicable in your jurisdiction, including export control laws and embargoes.
