### ISSUE TITLE
Where can i find the plip_model.pth file?

### ISSUE THREAD

**Issue by stbidtf** [vinid/path_eval#21]
The weight file I got from HF(https://huggingface.co/vinid/plip/tree/main) doesn't match here
![Snipaste_2024-03-24_14-55-03](https://github.com/PathologyFoundation/plip/assets/84228416/8152b310-8e32-4c0d-9d8a-3e9709b29b09)

**Comment by vinid** [comment]
Hello!!!

Yes you are right, the code we shared was used for training. We then converted the model to the huggingface format.

We don't have the clip compatible weights
