### ISSUE TITLE
plip model weights

### ISSUE THREAD

**Issue by ismeXQ** [vinid/path_eval#26]
Hello!

Where can I download the plip model weights? 

Can you provide me with the download link?

Thank you for any help you can provide!

**Comment by vinid** [comment]
Weights are here: https://huggingface.co/vinid/plip

Hope this helps!

**Comment by ismeXQ** [comment]
> Weights are here: https://huggingface.co/vinid/plip
> 
> Hope this helps!

Thank you for your reply, the help you provided is very useful.

I have one more question for your help.

In the provided plip model code "Reproduce Linear Probing.ipynb" file, you have given a path i.e. plip_path = “/path/to/plip”, is it the model weights that are decentralized under this path?

Where exactly can I get this weight?

**Comment by vinid** [comment]
We unfortunately don't have those weights anymore. You can either convert the weights back to clip format or you can use PLIP's API to generate the embeddings!

**Comment by ismeXQ** [comment]
> We unfortunately don't have those weights anymore. You can either convert the weights back to clip format or you can use PLIP's API to generate the embeddings!

Okay, thanks for your help.
