### ISSUE TITLE
Releasing code for preprocessing raw WSI data

### ISSUE THREAD

**Issue by ff98li** [vinid/path_eval#8]
Thank you for sharing this amazing pathological CLIP model! Very interesting work.

I wonder if by any chance the scripts for preprocessing raw whole-slide images (as in the case of DigestPath) will also be released. This will make it much easier for users who would like to play around with the model using their own WSI datasets. I was trying to perform the patchfication of WSI data following your paper, but not sure if I reproduced it properly.

Thank you!

**Comment by huangzhii** [comment]
That is a good idea. We will release the code for pre-processing external dataset soon!

**Comment by huangzhii** [comment]
The instruction to reproduce the validation dataset is now available at https://github.com/PathologyFoundation/plip/tree/main/reproducibility/generate_validation_datasets
